# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8ab23499236567486cd972f772b5967a54d831074913de561433dfd2c3b2b77c0ca098650a81c7b38dca27fac342d083f909d9cba04a5fc057a897324a23f1

test:
  secret_key_base: 6ac8ba267531ae066a83893ea608bb454ea1ba1558c1aa520daca056cd23fc87d3cf5aea0f7ba96033f8fa7eca32d7f2ceba7776c056cb35c3ab24a0e194e99c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
